default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  pool: 5
  timeout: 5000
  encoding: utf8
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: "<%= ENV['DB_PASSWORD'] || 'root' %>"
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'finance_dev' %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'finance_test' %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'finance_production' %>
  pool: 10
